version: "3"

services:

    sns-postgres:
      image: debezium/postgres:13-alpine
      environment:
        - POSTGRES_DATABASE=sns_dev
        - POSTGRES_USER=sns_dev
        - POSTGRES_PASSWORD=sns_dev
      ports:
        - 5432:5432
      volumes:
        - postgres-data:/data/db

volumes:
  postgres-data: